kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: argocd-clusterrolebinding
subjects:
- kind: ServiceAccount
  name: argocd-application-controller
  namespace: mathieu-argo
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: ""
